version: 2.1
orbs:
  node: circleci/node@3.0.0

jobs:
  test-client:
    executor:
      name: node/default
    steps:
      - checkout
      - run:
          command: yarn --ignore-engines
          name: Ignore engine versions
      - run:
          command: yarn --cwd ./client/ install --frozen-lockfile
          name: Installing client packages
      - run:
          command: yarn --cwd ./client/ run test
          name: Running client tests
          
  test-server:
    executor:
      name: node/default
    steps:
      - checkout
      - run:
          command: npm --ignore-engines
          name: Ignore engine versions
      - run:
          command: npm --prefix ./server/ install
          name: Installing server
      - run:
          command: npm --prefix ./server/ run test
          name: Running server tests

workflows:
  Tests:
    jobs:
      - test-client:
          name: Client test job
