version: 2.1

orbs:
  node: circleci/node@4.1

jobs:
  test-client:
    docker:
      - image: cimg/node:15.1
    steps:
      - checkout
      - run:
          command: yarn --ignore-engines
          name: Ignoring engine versions
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn test
          name: Running client tests
          
workflows:
  Tests:
    jobs:
      run:
        command: cd client/
        name: Changing directory to client folder
      - test-client:
          name: Client test job
