jobs:
  test-client:
    executor:
      name: node/default
    steps:
      - run:
        command: cd client/
        name: Changing directory to client folder
      - checkout
      - run:
          command: yarn --ignore-engines
          name: Ignoring engine versions
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn test
          name: Running client tests
workflows:
  Tests:
    jobs:
      - test-client:
          name: Client test job
          version: '15.1'
