version: 2.1
orbs:
  node: circleci/node@3.0.0

jobs:
  test-client:
    executor:
      name: node/default
    steps:
      - checkout
      - run:
          command: cd client/
          name: Changing directory to client folder
      - run:
          command: yarn --ignore-engines
          name: Ignoring engine versions
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn test
          name: Running client tests
      - run:
          command: cd ../
          name: Changing back to root dir
workflows:
  Tests:
    jobs:
      - test-client:
          name: Client test job
