name: Deploy server to heroku

'on':
  push:
    branches:
      - develop
      - ft-server
 
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Deploy to Heroku
        uses: onekiloparsec/heroku-node-deploy-subfolder@v1.1.0
        with:
          # Your Heroku API key. This will be used for authentication. You can find it in your Heroku account settings
          api_key: '${{ secrets.HEROKU_API_KEY }}'
          # The email of your Heroku account (needed for auth).
          email:  '${{ secrets.HEROKU_ACCOUNT_EMAIL }}'
          # The app name to use for deploying/updating
          app_name: '${{ secrets.APP_NAME }}'
          # The Heroku branch name that you would like to deploy to (`master` or `main`).
          heroku_branch: `main`
          # The subfolder where your built code is sitted, e.g. `dist`.
          subfolder: '../server'
        